HP_LIBRARY_DE = {
    "H200": "Instabil, explosiv.", "H201": "Explosiv, Gefahr der Massenexplosion.",
    "H202": "Explosiv; große Gefahr durch Splitter, Spreng- und Wurfstücke.",
    "H203": "Explosiv; Gefahr durch Feuer, Luftdruck oder Splitter, Spreng- und Wurfstücke.",
    "H204": "Gefahr durch Feuer oder Splitter, Spreng- und Wurfstücke.",
    "H205": "Gefahr der Massenexplosion bei Feuer.",
    "H220": "Extrem entzündbares Gas.",
    "H221": "Entzündbares Gas.",
    "H222": "Extrem entzündbares Aerosol.",
    "H223": "Entzündbares Aerosol.",
    "H224": "Flüssigkeit und Dampf extrem entzündbar.",
    "H225": "Flüssigkeit und Dampf leicht entzündbar.",
    "H226": "Flüssigkeit und Dampf entzündbar.",
    "H228": "Entzündbarer Feststoff.",
    "H240": "Erwärmung kann Explosion verursachen.",
    "H241": "Erwärmung kann Brand oder Explosion verursachen.",
    "H242": "Erwärmung kann Brand verursachen.",
    "H250": "Entzündet sich in Berührung mit Luft von selbst.",
    "H251": "Selbsterhitzungsfähig, kann sich selbst erhitzen; kann in Brand geraten.",
    "H252": "In großen Mengen selbsterhitzungsfähig; kann in Brand geraten.",
    "H260": "In Berührung mit Wasser entstehen entzündbare Gase, die sich spontan entzünden können.",
    "H261": "In Berührung mit Wasser entstehen entzündbare Gase.",
    "H270": "Kann Brand verursachen oder verstärken; Oxidationsmittel.",
    "H271": "Kann Brand oder Explosion verursachen; starkes Oxidationsmittel.",
    "H272": "Kann Brand verstärken; Oxidationsmittel.",
    "H280": "Enthält Gas unter Druck; kann bei Erwärmung explodieren.",
    "H281": "Enthält tiefkaltes Gas; kann Kälteverbrennungen oder -Verletzungen verursachen.",
    "H290": "Kann gegenüber Metallen korrosiv sein.",
    "H300": "Lebensgefährlich bei Verschlucken.",
    "H301": "Giftig bei Verschlucken.",
    "H302": "Gesundheitsschädlich bei Verschlucken.",
    "H304": "Kann bei Verschlucken and Eindringen in die Atemwege tödlich sein.",
    "H310": "Lebensgefahr bei Hautkontakt.",
    "H311": "Giftig bei Hautkontakt.",
    "H312": "Gesundheitsschädlich bei Hautkontakt.",
    "H314": "Verursacht schwere Verätzungen der Haut und schwere Augenschäden.",
    "H315": "Verursacht Hautreizungen.",
    "H317": "Kann allergische Hautreaktionen verursachen.",
    "H318": "Verursacht schwere Augenschäden.",
    "H319": "Verursacht schwere Augenreizung.",
    "H330": "Lebensgefahr bei Einatmen.",
    "H331": "Giftig bei Einatmen.",
    "H332": "Gesundheitsschädlich bei Einatmen.",
    "H334": "Kann bei Einatmen Allergie, asthmaartige Symptome oder Atembeschwerden verursachen.",
    "H335": "Kann die Atemwege reizen.",
    "H336": "Kann Schläfrigkeit und Benommenheit verursachen.",
    "H340": "Kann genetische Defekte verursachen.",
    "H341": "Kann vermutlich genetische Defekte verursachen.",
    "H350": "Kann Krebs erzeugen.",
    "H351": "Kann vermutlich Krebs erzeugen.",
    "H360": "Kann die Fruchtbarkeit beeinträchtigen oder das Kind im Mutterleib schädigen.",
    "H361": "Kann vermutlich die Fruchtbarkeit beeinträchtigen oder das Kind im Mutterleib schädigen.",
    "H362": "Kann Säuglinge über die Muttermilch schädigen.",
    "H370": "Schädigt die Organe.",
    "H371": "Kann die Organe schädigen.",
    "H372": "Schädigt die Organe bei längerer oder wiederholter Exposition.",
    "H373": "Kann die Organe schädigen bei längerer oder wiederholter Exposition.",
    "H300+H310": "Lebensgefahr bei Verschlucken oder Hautkontakt.",
    "H300+H330": "Lebensgefahr bei Verschlucken oder Einatmen.",
    "H310+H330": "Lebensgefahr bei Hautkontakt oder Einatmen.",
    "H300+H310+H330": "Lebensgefahr bei Verschlucken, Hautkontakt oder Einatmen.",
    "H301+H311": "Giftig bei Verschlucken oder Hautkontakt.",
    "H301+H331": "Giftig bei Verschlucken oder Einatmen.",
    "H311+H331": "Giftig bei Hautkontakt oder Einatmen.",
    "H301+H311+H331": "Giftig bei Verschlucken, Hautkontakt oder Einatmen.",
    "H302+H312": "Gesundheitsschädlich bei Verschlucken oder Hautkontakt.",
    "H302+H332": "Gesundheitsschädlich bei Verschlucken oder Einatmen.",
    "H312+H332": "Gesundheitsschädlich bei Hautkontakt oder Einatmen.",
    "H302+H312+H332": "Gesundheitsschädlich bei Verschlucken, Hautkontakt oder Einatmen.",
    "H400": "Sehr giftig für Wasserorganismen.",
    "H410": "Sehr giftig für Wasserorganismen, mit langfristiger Wirkung.",
    "H411": "Giftig für Wasserorganismen, mit langfristiger Wirkung.",
    "H412": "Schädlich für Wasserorganismen, mit langfristiger Wirkung.",
    "H413": "Kann für Wasserorganismen schädlich sein, mit langfristiger Wirkung.",
    "H420": "Schädigt die öffentliche Gesundheit und die Umwelt durch Ozonabbau in der äußeren Atmosphäre.",
    "EUH001": "In trockenem Zustand explosionsgefährlich.",
    "EUH006": "Mit und ohne Luft explosionsfähig.",
    "EUH014": "Reagiert heftig mit Wasser.",
    "EUH018": "Kann bei Verwendung explosionsfähige/entzündbare Dampf/Luft-Gemische bilden.",
    "EUH019": "Kann explosionsfähige Peroxide bilden.",
    "EUH029": "Entwickelt bei Berührung mit Wasser giftige Gase.",
    "EUH031": "Entwickelt bei Berührung mit Säure giftige Gase.",
    "EUH032": "Entwickelt bei Berührung mit Säure sehr giftige Gase.",
    "EUH044": "Explosionsgefahr bei Erhitzen unter Einschluss.",
    "EUH066": "Wiederholter kontakt kann zu spröder oder rissiger Haut führen.",
    "EUH070": "Giftig bei Berührung mit den Augen.",
    "EUH071": "Wirkt ätzend auf die Atemwege.",
    "EUH201": "Enthält Blei. Nicht für den Anstrich von Gegenständen verwenden, die von Kindern gekaut oder gelutscht werden könnten.",
    "EUH201A": "Achtung! Enthält Blei.",
    "EUH202": "Cyanacrylat. Gefahr. Klebt innerhalb von Sekunden Haut und Augenlider zusammen. Darf nicht in die Hände von Kindern gelangen.",
    "EUH203": "Enthält Chrom (VI). Kann allergische Reaktionen hervorrufen.",
    "EUH204": "Enthält Isocyanate. Kann allergische Reaktionen hervorrufen.",
    "EUH205": "Enthält epoxidhaltige Verbindungen. Kann allergische Reaktionen hervorrufen.",
    "EUH206": "Achtung! Nicht zusammen mit anderen Produkten verwenden, da gefährliche Gase freigesetzt werden können.",
    "EUH207": "Achtung! Enthält Cadmium. Bei der Verwendung entstehen gefährliche Dämpfe. Hinweise des Herstellers beachten. Sicherheitsanweisungen einhalten.",
    "EUH208": "Enthält sensibilisierende Stoffe. Kann allergische Reaktionen hervorrufen.",
    "EUH209": "Kann bei Verwendung leicht entzündbar werden.",
    "EUH209A": "Kann bei Verwendung entzündbar werden.",
    "EUH210": "Sicherheitsdatenblatt auf Anfrage erhältlich.",
    "EUH401": "Zur Vermeidung von Risiken für Mensch und Umwelt die Gebrauchsanleitung einhalten.",
    "H350i": "Kann beim Einatmen Krebs erzeugen.",
    "H360F": "Kann die Fruchtbarkeit beeinträchtigen.",
    "H360D": "Kann das Kind im Mutterleib schädigen.",
    "H361f": "Kann vermutlich die Fruchtbarkeit beeinträchtigen.",
    "H361d": "Kann vermutlich das Kind im Mutterleib schädigen.",
    "H360FD": "Kann die Fruchtbarkeit beeinträchtigen. Kann das Kind im Mutterleib schädigen.",
    "H361fd": "Kann vermutlich die Fruchtbarkeit beeinträchtigen. Kann vermutlich das Kind im Mutterleib schädigen.",
    "H360Fd": "Kann die Fruchtbarkeit beeinträchtigen. Kann vermutlich das Kind im Mutterleib schädigen.",
    "H360Df": "Kann das Kind im Mutterleib schädigen. Kann vermutlich die Fruchtbarkeit beeinträchtigen.",
    "P101": "Ist ärztlicher Rat erforderlich, Verpackung oder Etikett bereithalten.",
    "P102": "Darf nicht in die Hände von Kindern gelangen.",
    "P103": "Vor Gebrauch Etikett lesen.",
    "P201": "Vor Gebrauch besondere Anweisungen einholen.",
    "P202": "Vor Handhabung sämtliche Sicherheitsratschläge lesen und verstehen.",
    "P210": "Von Hitze/Funken/offener Flamme/heißen Oberflächen fernhalten. Nicht rauchen.",
    "P211": "Nicht in offene Flamme oder andere Zündquelle sprühen.",
    "P220": "Von Kleidung/brennbaren Materialien fernhalten/entfernt aufbewahren.",
    "P221": "Vermischung mit brennbaren Stoffen unter allen Umständen vermeiden.",
    "P222": "Berührung mit Luft vermeiden.",
    "P223": "Berührung mit Wasser wegen heftiger Reaktion und möglichem Aufflammen unbedingt vermeiden.",
    "P230": "Feucht halten mit …",
    "P231": "Unter inertem Gas handhaben.",
    "P232": "Vor Feuchtigkeit schützen.",
    "P233": "Behälter dicht verschlossen halten.",
    "P234": "Nur im Originalbehälter aufbewahren.",
    "P235": "Kühl halten.",
    "P240": "Behälter und zu befüllende Anlage erden.",
    "P241": "Explosionsgeschützte elektrische Anlagen/Lüftungsanlagen/Beleuchtungsanlagen verwenden.",
    "P242": "Nur funkenfreies Werkzeug verwenden.",
    "P243": "Maßnahmen gegen elektrostatische Aufladungen treffen.",
    "P244": "Druckminderventile frei von Fett und Öl halten.",
    "P250": "Nicht schleifen/stoßen/reiben.",
    "P251": "Behälter steht unter Druck: Nicht durchstechen oder verbrennen, auch nicht nach der Verwendung.",
    "P260": "Staub/Rauch/Gas/Nebel/Dampf/Aerosol nicht einatmen.",
    "P261": "Einatmen von Staub/Rauch/Gas/Nebel/Dampf/Aerosol vermeiden.",
    "P262": "Nicht in die Augen, auf die Haut oder auf die Kleidung gelangen lassen.",
    "P263": "Berührung in der Schwangerschaft/der Stillzeit vermeiden.",
    "P264": "Nach Handhabung gründlich waschen.",
    "P270": "Bei Verwendung dieses Produkts nicht essen, trinken oder rauchen.",
    "P271": "Nur im Freien oder in gut belüfteten Räumen verwenden.",
    "P272": "Kontaminierte Arbeitskleidung nicht außerhalb des Arbeitsplatzes tragen.",
    "P273": "Freisetzung in die Umwelt vermeiden.",
    "P280": "Schutzhandschuhe/Schutzkleidung/Augenschutz/Gesichtsschutz tragen.",
    "P281": "Vorgeschriebene persönliche Schutzausrüstung verwenden.",
    "P282": "Schutzhandschuhe/Gesichtsschild/Augenschutz mit Kälteisolierung tragen.",
    "P283": "Feuerbeständige/flammbeständige/feuerhemmende/flammhemmende Kleidung tragen.",
    "P284": "Atemschutz tragen.",
    "P285": "Bei unzureichender Belüftung Atemschutz tragen.",
    "P231+P232": "Unter inertem Gas handhaben. Vor Feuchtigkeit schützen.",
    "P235+P410": "Kühl halten. Vor Sonnenbestrahlung schützen.",
    "P301": "BEI VERSCHLUCKEN:",
    "P302": "BEI BERÜHRUNG MIT DER HAUT:",
    "P303": "BEI BERÜHRUNG MIT DER HAUT (oder dem Haar):",
    "P304": "BEI EINATMEN:",
    "P305": "BEI BERÜHRUNG MIT DEN AUGEN:",
    "P306": "BEI BERÜHRUNG MIT DER KLEIDUNG:",
    "P307": "BEI Exposition:",
    "P308": "BEI Exposition oder Verdacht:",
    "P309": "BEI Exposition oder Unwohlsein:",
    "P310": "Sofort GIFTINFORMATIONSZENTRUM oder Arzt anrufen.",
    "P311": "GIFTINFORMATIONSZENTRUM oder Arzt anrufen.",
    "P312": "Bei Unwohlsein GIFTINFORMATIONSZENTRUM oder Arzt anrufen.",
    "P313": "Ärztlichen Rat einholen / ärztliche Hilfe hinzuziehen.",
    "P314": "Bei Unwohlsein ärztlichen Rat einholen / ärztliche Hilfe hinzuziehen.",
    "P315": "Sofort ärztlichen Rat einholen / ärztliche Hilfe hinzuziehen.",
    "P320": "Gezielte Behandlung dringend erforderlich.",
    "P321": "Besondere Behandlung.",
    "P322": "Gezielte Maßnahmen.",
    "P330": "Mund ausspülen.",
    "P331": "KEIN Erbrechen herbeiführen.",
    "P332": "Bei Hautreizung:",
    "P333": "Bei Hautreizung oder -ausschlag:",
    "P334": "In kaltes Wasser tauchen / nassen Verband anlegen.",
    "P335": "Lose Partikel von der Haut abbürsten.",
    "P336": "Vereiste Bereiche mit lauwarmem Wasser auftauen. Betroffenen Bereich nicht reiben.",
    "P337": "Bei anhaltender Augenreizung:",
    "P338": "Eventuell vorhandene Kontaktlinsen nach Aufmerksamkeit entfernen. Weiter ausspülen.",
    "P340": "Die betroffene Person an die frische Luft bringen und in einer Position ruhigstellen, die das Atmen erleichtert.",
    "P341": "Bei Atembeschwerden die betroffene Person an die frische Luft bringen und in einer Position ruhigstellen, die das Atmen erleichtert.",
    "P342": "Bei Symptomen der Atemwege:",
    "P350": "Behutsam mit viel Wasser und Seife waschen.",
    "P351": "Einige Minuten lang behutsam mit Wasser ausspülen.",
    "P352": "Mit viel Wasser und Seife waschen.",
    "P353": "Haut mit Wasser abwaschen/duschen.",
    "P360": "Vor Ablegen der Kleidung kontaminierte Kleidung und Haut sofort mit reichlich Wasser abwaschen.",
    "P361": "Alle kontaminierten Kleidungsstücke sofort ausziehen.",
    "P362": "Kontaminierte Kleidung ausziehen und vor erneutem Tragen waschen.",
    "P363": "Kontaminierte Kleidung vor erneutem Tragen waschen.",
    "P310+P330+P331": "BEI VERSCHLUCKEN: Mund ausspülen. KEIN Erbrechen herbeiführen.",
    "P302+P334": "BEI BERÜHRUNG MIT DER HAUT: In kaltes Wasser tauchen/nassen Verband anlegen.",
    "P302+P350": "BEI BERÜHRUNG MIT DER HAUT: Vorsichtig mit reichlich Wasser und Seife waschen.",
    "P302+P352": "BEI BERÜHRUNG MIT DER HAUT: Mit viel Wasser und Seife waschen.",
    "P303+P361+P353": "BEI BERÜHRUNG MIT DER HAUT (oder dem Haar): Alle kontaminierten Kleidungsstücke sofort ausziehen. Haut mit Wasser abwaschen/duschen.",
    "P304+P340": "BEI EINATMEN: An die frische Luft bringen und in einer Position ruhigstellen, die das Atmen erleichtert.",
    "P304+P341": "BEI EINATMEN: Bei Atembeschwerden die betroffen Person an die frische Luft bringen und in einer Position ruhigstellen, die das Atmen erleichtert.",
    "P305+P351+P338": "BEI BERÜHRUNG MIT DEN AUGEN: Einige Minuten lang vorsichtig mit Wasser ausspülen. Eventuell. vorhandene Kontaktlinsen nach Möglichkeit entfernen. Weiter ausspülen.",
    "P306+P360": "BEI BERÜHRUNG MIT DER KLEIDUNG: Vor Ablegen der Kleidung kontaminierte Kleidung und Haut sofort mit viel Wasser abwaschen.",
    "P307+P311": "BEI Exposition: GIFTINFORMATIONSZENTRUM oder Arzt anrufen.",
    "P308+P313": "BEI Exposition oder Verdacht: Ärztlichen Rat einholen/ärztliche Hilfe hinzuziehen.",
    "P309+P311": "BEI Exposition oder Unwohlsein: GIFTINFORMATIONSZENTRUM oder Arzt anrufen.",
    "P332+P313": "Bei Hautreizung: Ärztlichen Rat einholen/ärztliche Hilfe hinzuziehen.",
    "P333+P313": "Bei Hautreizung oder -ausschlag: Ärztlichen Rat einholen/ärztliche Hilfe hinzuziehen.",
    "P337+P313": "Bei anhaltender Augenreizung: Ärztlichen Rat einholen/ärztliche Hilfe hinzuziehen.",
    "P342+P311": "Bei Symptomen der Atemwege: GIFTINFORMATIONSZENTRUM oder Arzt anrufen.",
    "P370+P376": "Bei Brand: Undichtigkeit beseitigen, falls gefahrlos möglich.",
    "P370+P378": "Bei Brand: … zum Löschen verwenden.",
    "P370+P380": "Bei Brand: Umgebung räumen.",
    "P370+P380+P375": "Bei Brand: Umgebung räumen. Wegen Explosionsgefahr Brand aus der Entfernung bekämpfen.",
    "P371+P380+P375": "Bei Großbrand und großen Mengen: Umgebung räumen. Wegen Explosionsgefahr Brand aus der Entfernung bekämpfen.",
    "P401": "Aufbewahren gemäß …",
    "P402": "An einem trockenen Ort aufbewahren.",
    "P403": "An einem gut belüfteten Ort aufbewahren.",
    "P404": "In einem geschlossenen Behälter aufbewahren.",
    "P405": "Unter Verschluss aufbewahren.",
    "P406": "In korrosionsbeständigem Behälter mit korrosionsbeständiger Innenauskleidung aufbewahren.",
    "P407": "Luftspalt zwischen Stapeln/Paletten lassen.",
    "P410": "Vor Sonnenbestrahlung schützen.",
    "P411": "Bei einer Temperatur von nicht mehr als … °C aufbewahren.",
    "P412": "Nicht Temperaturen über 50 °C/122 °F aussetzen.",
    "P413": "Schüttgut in Mengen von mehr als … kg bei einer Temperatur von nicht mehr als … °C aufbewahren.",
    "P420": "Von anderen Materialien entfernt aufbewahren.",
    "P422": "Inhalt unter … aufbewahren.",
    "P402+P404": "An einem trockenen Ort aufbewahren. In einem geschlossenen Behälter aufbewahren.",
    "P403+P233": "An einem gut belüfteten Ort aufbewahren. Behälter dicht verschlossen halten.",
    "P403+P235": "An einem gut belüfteten Ort aufbewahren. Kühl halten.",
    "P410+P403": "Vor Sonnenbestrahlung schützen. An einem gut belüfteten Ort aufbewahren.",
    "P410+P412": "Vor Sonnenbestrahlung schützen. Nicht Temperaturen über 50 °C/122 °F aussetzen.",
    "P411+P235": "Bei einer Temperatur von nicht mehr als … °C aufbewahren. Kühl halten.",
    "P501": "Inhalt/Behälter … zuführen."
}
