when:
  branch: ["develop", "main"]
  event: ["pull_request", "push", "tag"]

steps:
  crates:
    image: codeberg.org/calciumdibromid/cabr2_ci:root
    pull: true
    when:
      path:
        - '.woodpecker/check.yml'
        - 'crates/**'
        - 'Cargo.lock'

    commands:
      - rustup default stable
      - rustc -V
      - cargo -V
      - cd crates # change dir to crates
      - cargo fmt --all --check
      - cargo clippy -p config -p error-ser -p load_save -p logger -p search -p types --all-features -- --deny clippy::all --deny warnings

  frontend:
    image: codeberg.org/calciumdibromid/cabr2_ci:root
    pull: true
    when:
      path:
        - '.woodpecker/check.yml'
        - 'frontend/src/**'
        - 'frontend/*.json'
        - 'frontend/*.js'
        - 'frontend/.prettierignore'
        - 'frontend/yarn.lock'
        - 'frontend/src-wasm/**'

    commands:
      - node -v
      - yarn --version
      - cd frontend # change dir to frontend
      - yarn install --frozen-lockfile
      - yarn prettier -c src
      - yarn lint

  webserver:
    image: codeberg.org/calciumdibromid/cabr2_ci:root
    pull: true
    depends_on: crates
    when:
      path:
        - '.woodpecker/check.yml'
        - 'webserver/**'
        - 'crates/**'
        - 'Cargo.lock'

    commands:
      - rustup default stable
      - rustc -V
      - cargo -V
      - cd webserver # change dir to webserver
      - cargo fmt --check
      - cargo clippy --locked --all-features -- --deny clippy::all --deny warnings

  tauri-app:
    image: codeberg.org/calciumdibromid/cabr2_ci:root
    pull: true
    depends_on: crates
    when:
      path:
        - '.woodpecker/check.yml'
        - 'frontend/src-tauri/**'
        - 'crates/**'
        - 'Cargo.lock'

    commands:
      - rustup default stable
      - rustc -V
      - cargo -V

      # Fix build
      - mkdir -p frontend/dist/CaBr2 && echo "Hello" > frontend/dist/CaBr2/index.html
      - cd frontend/src-tauri # change dir to frontend/src-tauri
      - cargo fmt --check
      - cargo clippy --locked --all-features -- --deny clippy::all --deny warnings

  wasm-lib:
    image: codeberg.org/calciumdibromid/cabr2_ci:root
    pull: true
    depends_on: crates
    when:
      path:
        - '.woodpecker/check.yml'
        - 'frontend/src-wasm/**'
        - 'crates/**'
        - 'Cargo.lock'

    commands:
      - rustup default stable
      - rustc -V
      - cargo -V
      - cd frontend/src-wasm # change dir to frontend/src-wasm
      - cargo fmt --check
      - cargo clippy --locked --all-features --target wasm32-unknown-unknown -- --deny clippy::all --deny warnings
