when:
  branch: ["develop", "main"]
  event: ["pull_request", "push", "tag"]

depends_on:
  - check

steps:
  rust:
    image: codeberg.org/calciumdibromid/cabr2_ci:root
    pull: true
    when:
      path:
        - '.woodpecker/build.yml'
        - 'crates/**'
        - 'Cargo.lock'
        - 'frontend/src-wasm/**'
        - 'frontend/src-tauri/**'
        - 'webserver/**'

    commands:
      - rustup default stable
      - rustc -V
      - cargo -V

      # Fix build
      - mkdir -p frontend/dist/CaBr2 && echo "Hello" > frontend/dist/CaBr2/index.html
      - cargo test --workspace --all-features

# enable when tests are available
  # frontend-web:
  #   image: codeberg.org/calciumdibromid/cabr2_ci:root
  #   pull: true
  #   group: build_together
  #   when:
  #     path:
  #       - '.woodpecker/build.yml'
  #       - 'frontend/src/**'
  #       - 'frontend/*.json'
  #       - 'frontend/*.js'
  #       - 'frontend/.prettierignore'
  #       - 'frontend/yarn.lock'
  #       - 'frontend/src-wasm/**'

  #   commands:
  #     - node -v
  #     - yarn --version
  #     - cd frontend # change dir to frontend
  #     - yarn install --frozen-lockfile
  #     # wasm lib is already built
  #     - yarn ng test
